### ISSUE TITLE
Don't ask for sudo more than once

### ISSUE THREAD

**Issue by m-roberts** [joshukraine/mac-bootstrap#26]
Readme says:
> WARNING: This script will ask for your sudo password multiple times. You'll need to babysit it for a while. 😉

One such solution:
https://github.com/mathiasbynens/dotfiles/blob/main/.macos#L9-L13

**Comment by joshukraine** [comment]
Hi, thanks for the suggestion! (Sorry for the late response. 😬) I actually do use that code in my bootstrap script. (https://github.com/joshukraine/mac-bootstrap/blob/cf4ab6af5492a2f539389c0e7fee0b4015642887/bootstrap#L86-L89) However, because we're also doing things like installing casks from Homebrew, you still have to type in your admin password more than once. I think in Mathias' case, he's just running that single script with no Homebrew installs.

Also of note is that my bootstrap script pulls in other "sub-scripts", namely laptop and macos-defaults. I don't believe the keep-alive sudo trick "descends" into sub-scripts, but I could be wrong. If you have a suggestion on how to handle this better, I'd love to hear it!
