### ISSUE TITLE
[Question] Use Brewfile from dotfiles

### ISSUE THREAD

**Issue by delneet** [joshukraine/mac-bootstrap#27]
Hi.

Is there a reason for not using the Brewfile from the [dotfiles](https://github.com/joshukraine/boostrap) repo?
Or is it mainly for not having dependencies?

**Comment by joshukraine** [comment]
> Hi.
> 
> Is there a reason for not using the Brewfile from the [dotfiles](https://github.com/joshukraine/boostrap) repo?
> Or is it mainly for not having dependencies?

Yes, the reason I do this is to speed up new setups. I've found that when setting up a new Mac (and especially when testing!) I don't necessarily want to wait for every last program to install. The issue here is more with casks than cli formulae. So I've reduced the casks to a minimum for bootstrap, then I can complete the process with a single command once I'm ready.
